[package]
name = "email-senderr"
version = "0.1.0"
edition = "2024"

[dependencies]
lettre = { version = "0.11", features = ["tokio1-native-tls", "hostname"] }
tokio = { version = "1", features = ["full"] }
config = "0.15.19"
